# Generated by Django 4.1.13 on 2024-08-30 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0002_usertask_remove_userprofile_user_delete_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='points_earned',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='tasks_completed',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(default=0)),
                ('task_completed', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
