# Generated by Django 4.1.13 on 2024-08-30 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0003_rename_points_earned_usertask_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_task',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_app.usertask'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
